### PR TITLE
Brief description of testing policy

### PR DESCRIPTION
**Pull request by mbrookeswebdev**
Hi all, can you please review the Testing Policy text in this PR and post any comments/suggestions if any. Thank you!

### CODE REVIEW

**Review by warrensearle — CHANGES_REQUESTED** [review]
Hey @mbrookeswebdev I've made some notes (below) which I think could be combined with your content.

---

The JAC aims to test early, often and throughout the discovery, design and build of our services.

No changes are allowed to our services unless they pass various automated and manual tests.

Our current (Sep 2021) testing steps for all changes (new features, improvements and fixes) are outlined below.

Developers run unit tests and lint checks in their local development environments before changes are pushed to our code repository.

All changes are pushed to new branches and are not allowed in our main code base until they have passed a number of checks: 

- Automated unit tests and lint checks are run along with automated code scanning to check for security vulnerabilities and coding errors.
- Changes are manually code reviewed by multiple developers.
- Changes are automatically deployed to preview URLs and manually tested by the product team and at least two user representatives (via the User Testing Group).

When all checks have passed the approved changes are merged into our main codebase and automatically deployed to our staging (pre-production) environment.

On staging the changes are manually verified and staging is also checked for regressions.

When all is ok the change will be released to production.

**Comment by mbrookeswebdev** [comment]
@warrensearle thank you! 🥇

**Review by HalcyonJAC — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
Great stuff, thanks @mbrookeswebdev 👍 
Note: we should put a reminder to refresh this document as the content will fairly soon be out of date / stale.

**Review by tomlovesgithub — APPROVED** [review]

**Review by joy-ade — APPROVED** [review]
Reviewed and approved by product team

**Pull request merged**
